### ISSUE TITLE
uuid

### ISSUE THREAD

**Issue by reharik** [jpoumailloux/jquery.ui.monthpicker#1]
hey you need to add this line of code to your MonthPicker function ( ~line 54 )
this.uuid =0;
otherwise when you go to create an id function _attachMonthpicker ~ line 148 you end up with an target id of dpNAN.  And all instances will have the same id so the date will always only populate one element regardless of which one you click on.
thx
r

**Comment by jpoumailloux** [comment]
Thanks for noticing the problem and sharing the fix, I have just commited it!
